DO $$
BEGIN
  CREATE TYPE "PaymentStatus" AS ENUM ('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "PricingMarket" AS ENUM ('LOCAL_PK', 'CHINA', 'INTERNATIONAL');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "DisplayCurrency" AS ENUM ('PKR', 'USD', 'CNY', 'GBP', 'AED', 'SAR', 'EUR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "itineraries"
ADD COLUMN IF NOT EXISTS "pricing_market" "PricingMarket" NOT NULL DEFAULT 'LOCAL_PK',
ADD COLUMN IF NOT EXISTS "display_currency" "DisplayCurrency" NOT NULL DEFAULT 'PKR',
ADD COLUMN IF NOT EXISTS "exchange_rate" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "display_total" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "security_cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "service_cost" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "bookings"
ADD COLUMN IF NOT EXISTS "payment_status" "PaymentStatus" NOT NULL DEFAULT 'UNPAID',
ADD COLUMN IF NOT EXISTS "payment_reference" TEXT,
ADD COLUMN IF NOT EXISTS "pricing_market" "PricingMarket" NOT NULL DEFAULT 'LOCAL_PK',
ADD COLUMN IF NOT EXISTS "display_currency" "DisplayCurrency" NOT NULL DEFAULT 'PKR',
ADD COLUMN IF NOT EXISTS "exchange_rate" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "display_total" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "service_cost" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "custom_trip_registrations"
ADD COLUMN IF NOT EXISTS "payment_status" "PaymentStatus" NOT NULL DEFAULT 'UNPAID',
ADD COLUMN IF NOT EXISTS "payment_reference" TEXT,
ADD COLUMN IF NOT EXISTS "pricing_market" "PricingMarket" NOT NULL DEFAULT 'LOCAL_PK',
ADD COLUMN IF NOT EXISTS "display_currency" "DisplayCurrency" NOT NULL DEFAULT 'PKR',
ADD COLUMN IF NOT EXISTS "exchange_rate" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "display_total" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "security_cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "service_cost" INTEGER NOT NULL DEFAULT 0;
